application:
  id: zara
  version: 1.0.0
  defaultLanguage: ca_ES
  
server:
  port: 8081
  
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      hbm2ddl:
        auto: none

env:
  db:
    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
