
CREATE TABLE PRICES (
	PRICE_LIST BIGINT NOT NULL
	PRODUCT_ID BIGINT NOT NULL, 
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	BRAND_ID BIGINT,
	PRIORITY BIGINT,
	PRICE REAL(2),
	CURR VARCHAR(50)
);

ALTER TABLE PRICES ADD CONSTRAINT "PRICES_PK" PRIMARY KEY (PRICE_LIST);
